id: P009186
initial_creation_type: ocr
source_metadata:
  id: bdr:W30067
  title: རྒྱལ་གྱི་ཤྲཱིའམ་རྩིབ་རིའི་གནས་བཤད་དད་གསུམ་འདྲེན་པའི་ཞིང་ས
  author: ''
  volumes:
    a67b8a8382094b4d91b77755520291a2:
      image_group_id: I1GS75029
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
